version: '3'

services: 
  app: 
    build: .
    container_name: app-bank
    ports: 
      - 3333:3333
    volumes: 
      - ./:/go/src
    depends_on: 
      - db

  db:
    image: postgres:9.4
    container_name: db-bank
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codebank
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    container_name: db-client-bank
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db