import { Button, Card, CardActions, CardContent, CardMedia, Grid, Typography } from '@material-ui/core'
import Head from 'next/head'
import Image from 'next/image'
import { Products, products } from '../model'
import Link from "next/link"
import { GetServerSideProps, NextPage } from 'next'
import localApi from '../services/localApi'

interface ProductsListPageProps {
  products: Products[]
}
const ProductsListPage: NextPage<ProductsListPageProps> = ({ products }) => {
  console.log(products)
  return (
    <div>
      <Head>
        <title>Catálogo de produtos</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Typography component="h1" variant="h3" color="textPrimary" gutterBottom>
        Produtos
      </Typography>
      <Grid container spacing={4}>
        {
          products.map((product, index) => (
            <Grid key={index} item xs={12} sm={6} md={4}>
              <Card>
                <CardMedia style={{ paddingTop: "56%" }} image={product.image_url} />
                <CardContent>
                  <Typography component="h2" variant="h5" gutterBottom>
                    {product.name}
                  </Typography>
                </CardContent>
                <CardActions>
                  <Link href="/products/[slug]" as={`/products/${product.slug}`} passHref>
                    <Button size="small" component="a" color="primary">Detalhes</Button>
                  </Link>
                </CardActions>
              </Card>
            </Grid>
          ))
        }
      </Grid>
    </div>
  )
}


export const getServerSideProps: GetServerSideProps = async (context) => {
  const products = await localApi.getProducts()
  return {
    props: {
      products
    }
  }
}

export default ProductsListPage